apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-volume-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: volume-class
  nfs:
    server: pmacs-nfs.canadacentral.cloudapp.azure.com
    path: "/dados/minio-datastore/"
